import { GoogleGenerativeAI } from "@google/generative-ai";
import ApplicationError from "../../middleware/applicationError.middleware.js";
export const generateTravelItinerary = async (prompt) => {
    console.log(`gemini api : ${process.env.GEMINI_API_KEY}`);
    const genAi = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
    const model = genAi.getGenerativeModel({ model: "gemini-2.5-flash-lite" });

    try {
        const result = await model.generateContent(prompt);
         const response = await result.response;
         const text = response.text()
        if (!text) {
            throw new Error("Empty itinerary generated by AI service");
        }
        return text;
    } catch (error) {
        console.error("Gemini API Error:", { message: error.message, stack: error.stack });
        // Invalid api
        if (error.message.includes("API key") || error.message.includes("authentication")) throw new ApplicationError(401, "Invalid Gemini API key");
        // Quota exceeded
        if (error.message.includes("quota") || error.message.includes("429")) throw new ApplicationError(429, "AI service quota exceeded. Please try again later.");
        // Safety filter block
        if (error.message.includes("SAFETY") || error.message.includes("blocked")) throw new ApplicationError(400, "Request blocked by AI safety filters.");
        // Network-related errors
        if (error.message.includes("fetch failed") || error.message.includes("network")) throw new ApplicationError(503, "Unable to connect to AI service.");
        // normal fallback
        throw new ApplicationError(500, "Failed to generate travel itinerary.");
    }
}